version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
  server:
    build: ./server
    depends_on:
      - mosquitto

